config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
    member do
      post :join
      post :quit
    end

    resources :reviews
  end

  namespace :account do
    resources :movies
    resources :reviews
  end

  root "movies#index"
  get "about/index"
  get 'about2', to: 'movies#about2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews
  validates :title, presence: true

  has_many :movie_relationships
  has_many :members, through: :movie_relationships, source: :user
end

app/models/movie_relationship.rb
class MovieRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :content, presence: true
  scope :recent, -> { order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_many :reviews
  has_many :movie_relationships
  has_many :participated_movies, :through => :movie_relationships, :source => :movie

  def is_member_of?(movie)
    participated_movies.include?(movie)
  end

  def join!(movie)
    participated_movies << movie
  end

  def quit!(movie)
    participated_movies.delete(movie)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    @movies = current_user.participated_movies
  end

end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = current_user.reviews
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :join, :quit]
  before_action :find_movie_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    if @movie.save
      current_user.join!(@movie)
      redirect_to movies_path, notice: "新增电影成功！"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to movies_path, notice: "编辑电影成功！"
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
      redirect_to movies_path, notice: "已删除电影 - "+@movie.title
  end

  def join
    @movie = Movie.find(params[:id])

    if !current_user.is_member_of?(@movie)
      current_user.join!(@movie)
      flash[:notice] = "收藏电影《" +@movie.title+ "》成功！"
    else
      flash[:warning] = "已收藏电影《" +@movie.title+ "》！"
    end

    redirect_to movie_path(@movie)
  end

  def quit
    @movie = Movie.find(params[:id])

    if current_user.is_member_of?(@movie)
      current_user.quit!(@movie)
      flash[:alert] = "已取消收藏电影《" +@movie.title+ "》！"
    else
      flash[:warning] = "你还未收藏电影《" +@movie.title+ "》！"
    end

    redirect_to movie_path(@movie)
  end

  def about2
  end


  private

  def movie_params
    params.require(:movie).permit(:title, :description)
  end

  def find_movie_and_check_permission
    @movie = Movie.find(params[:id])

    if current_user != @movie.user
      redirect_to root_path, alert: "你没有权限这样做！"
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :update, :edit, :destroy]

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user

    if @review.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to account_reviews_path, notice: "编辑成功！"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.destroy

      redirect_to account_reviews_path, notice: "删除成功！"
  end


  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:warning] = "这是一个电影评论网站"
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def render_movie_description(movie)
    simple_format(movie.description)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>this is about</h1>
<%= link_to('Back', movies_path) %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2016 Movie Review
    <br>
    Design by
    <a href="/" target="_new">EmileSu</a>
    <%= link_to("about", about_index_path) %>
    <%= link_to("about2", about2_path) %>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse row" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">Movie Review</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %></li>
          <li><%= link_to("登录", new_user_session_path) %></li>
        <% else %>
          <li class= "dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("我推荐的电影", account_movies_path) %></li>
              <li><%= link_to("我发表的影评", account_reviews_path) %></li>
              <li class= "divider"></li>
              <li><%= link_to("退出", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

    <%= render "common/footer" %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "提交", class: "btn btn-default", data: {disable_with: "Submiting..."} %>
<% end %>

app/views/movies/about2.html.erb
<h1>this is about2</h1>
<%= link_to('Back', movies_path) %>

app/views/movies/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2>编辑电影</h2>
  <hr>

  <%= render "form" %>
</div>

app/views/movies/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("新建电影", new_movie_path, class: "btn btn-default pull-right") %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <td>电影名称</td>
        <td>简介</td>
        <td>创建者</td>
      </tr>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= link_to(movie.title, movie_path(movie)) %></td>
          <td><%= render_movie_description(movie) %></td>
          <td><%= movie.user.email %></td>
          <td>
            <% if current_user && current_user == movie.user %>
              <%= link_to("编辑", edit_movie_path(movie), class: "btn btn-sm btn-default" )%>
              <%= link_to("删除", movie_path(movie), class: "btn btn-sm btn-default", method: :delete, data:{ confirm: "你确定删除吗？"}) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/movies/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2>新增电影</h2>
  <hr>

  <%= render "form"  %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <div class="group">

    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@movie) %>
        <label class="label label-success">已收藏</label>
        <%= link_to("取消收藏", quit_movie_path(@movie), method: :post, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning">未收藏</label>
        <%= link_to("收藏", join_movie_path(@movie), method: :post, class: "btn btn-default") %>
      <% end %>
    </span>

    <% if current_user && current_user.is_member_of?(@movie)%>
      <%= link_to("发表影评", new_movie_review_path(@movie), class: "btn btn-default pull-right") %>
    <% end %>
    <% if current_user && current_user == @movie.user %>
      <%= link_to("编辑", edit_movie_path(@movie), class: "btn btn-default pull-right") %>
    <% end %>
  </div>

  <h2><%= @movie.title %></h2>
  <p style="font-size:10px; margin-bottom:30px;">创建时间:<%= @movie.created_at%></p>
  <p><%= @movie.description %></p>

  <table class="table">
    <thead>
      <tr>
        <th>影片评价</th>
        <th>发表者</th>
        <th>发表时间</th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.content %></td>
          <td><%= review.user.email %></td>
          <td><%= review.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= will_paginate @reviews %>
  </div>
</div>

app/views/reviews/edit.html.erb
<h2 class="text-center">编辑《<%= @movie.title %>》影评</h2>

<div class="col-md-8 col-md-offset-2">
  <%= simple_form_for [@movie,@review] do |f| %>
    <div class="form-froup">
      <%= f.input :content, input_html: { class: "form_control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "提交", disable_with: "Submiting...", class: "btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h2 class="text-center">新增《<%= @movie.title %>》影评</h2>

<div class="col-md-8 col-md-offset-2">
  <%= simple_form_for [@movie,@review] do |f| %>
    <div class="form-froup">
      <%= f.input :content, input_html: { class: "form_control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "提交", disable_with: "Submiting...", class: "btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="container">
<h1>这是一个电影评论网站</h1>
</div>